In [1]:
import numpy as np
# Numeric Python
# ndarray = n-dimensional array

In [2]:
np1 = np.array([0,1,2,3])
np1.shape

(4,)

In [3]:
np2 = np.arange(11)
np2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np3 = np.zeros(10)

In [5]:
np3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np3[0]

np.float64(0.0)

In [7]:
np4 = np.zeros((2,10))
print(np4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
np5 = np.full((2,10), 10)
np5