In [1]:
import numpy as np

#slicing numpy array

np1 = np.array([1,2,3,4,5])
print(np1[1:3])

[2 3]


In [2]:
print(np1[1:])

[2 3 4 5]


In [3]:
print(np1[-4:-1])

[2 3 4]


In [4]:
print(np1[0::2])

[1 3 5]


In [5]:
print(np1[::3])

[1 4]


In [7]:
twod = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(twod[0,3])

4


In [8]:
print(twod[0:2, 0:4])

[[1 2 3 4]
 [6 7 8 9]]


In [9]:
#__________row_index:until_row_index, starting_col_index:until_col_index:step
print(twod[0:2, 0:4:2])

[[1 3]
 [6 8]]
